---
- hosts: ubuntu
  become: yes
  tasks:

  - name: Add user to remote hosts
    user: name=ansible-admin groups=sudo shell=/bin/bash

  - name: Add SSH keys to remote hosts
    authorized_key: user=ansible-admin key="{{ lookup('file', "/etc/ansible/common/files/id_rsa.pub") }}"

- hosts: centos7
  become: yes
  tasks:

  - name: Add user to remote hosts
    user: name=ansible-admin groups=wheel shell=/bin/bash

  - name: Add SSH keys to remote hosts
    authorized_key: user=ansible-admin key="{{ lookup('file', "/etc/ansible/common/files/id_rsa.pub") }}"
