---

- hosts: all
  become: yes
  tasks:

  - name: Install Zabbix-release on CentOS 7

    yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm

    when: ansible_os_family == "RedHat"

  - name: Install zabbix-agent

    yum:
         name: zabbix-agent
         state: present

    when:
        ansible_os_family == "RedHat"

    notify:
        zabbix-agent systemd

  - name: Install zabbix agent on Ubuntu

    become: yes
    apt:
        name: zabbix-agent
        state: present

    when:
        ansible_os_family == "Debian"

  - name: Install zabbix release package

    become: yes 
    apt:
       deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
       state: present
    when:
         ansible_os_family == "Debian"
    notify:
        zabbix-agent systemd

  handlers:

  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
